format_version: 3
pipelines:
  Test.SLE_BCI_15SP3.RepoPublisher:
    group: BCI
    lock_behavior: unlockWhenFinished
    materials:
      git:
        git: https://github.com/openSUSE/openSUSE-release-tools.git
        destination: scripts
    environment_variables:
        OSC_CONFIG: /home/go/config/oscrc-totest-manager
        BCI_TOKEN: '{{SECRET:[opensuse.secrets][BCI_TOKEN]}}'
    stages:
    - Run:
        approval: manual
        resources:
        - staging-bot
        tasks:
        - script: |
            export PYTHONPATH=scripts
            ./scripts/gocd/bci_repo_publish.py -A https://api.suse.de --verbose --debug run "--token=$BCI_TOKEN" 15-SP3
