format_version: 3
pipelines:
  ContainerCleanerTest.Tumbleweed:
    group: openSUSE.Checkers
    lock_behavior: unlockWhenFinished
    environment_variables:
      OSC_CONFIG: /home/go/config/oscrc-totest-manager
    materials:
      script:
        git: https://github.com/Vogtinator/osc-plugin-factory.git
        branch: containercleaner
        destination: scripts-cc
    timer:
      spec: 0 0-23/2 * ? * *
      only_on_changes: false
    stages:
    - Run:
        approval: manual
        resources:
        - staging-bot
        tasks:
        - script: |-
            scripts-cc/container_cleaner.py --debug --dry run home:favogt:releasetest:Containers
